# In this notebook, its more about the fundamentals of tensors using Tensorflow



In [ ]:
# Import TensorFLow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tesor (ndim stands for number of dimesion)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of the vector
vector.ndim

1

In [ ]:
# Create a matrix(has more than one dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check the dimension of the matrix
matrix.ndim

2

In [ ]:
# Create anothter type of matrix
ano_matrix = tf.constant([[3., 2.],
                          [4., 3.],
                          [4., 8.]], dtype=tf.float16) #specifying the data type

ano_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[3., 2.],
       [4., 3.],
       [4., 8.]], dtype=float16)>

In [ ]:
# check the nnumber of dimensions
ano_matrix.ndim

2

In [ ]:
#  Creating a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# Check the number of dimension
tensor.ndim

3

In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor 

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# checking the indexing
changeable_tensor[1] 

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Changing the values in the index
changeable_tensor[1].assign(10)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Creating random tensors 
random_1 = tf.random.Generator.from_seed(42)  #set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# Shuffle the order of elements in a tensor
not_shuffled = tf.constant([[8, 9],
                            [3, 6],
                            [2, 7]])
not_shuffled
tf.random.shuffle(not_shuffled)

# adding a seed(This creates a random shuffe)
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled, seed = 7)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 6],
       [8, 9],
       [2, 7]], dtype=int32)>

In [ ]:
A = tf.constant([[2,3,4],
                [2, 4, 5]])
# A.ndim
# tf.size(A).numpy()
# print(tf.shape(A).numpy())
# A.shape

In [ ]:
# a = tf.zeros([2, 2])
# a
b = tf.ones([3, 4])
b = tf.reshape(b, [2,3,2])
b + 8, b

(<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
 array([[[9., 9.],
         [9., 9.],
         [9., 9.]],
 
        [[9., 9.],
         [9., 9.],
         [9., 9.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
 array([[[1., 1.],
         [1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.],
         [1., 1.]]], dtype=float32)>)

In [ ]:
 b.dtype #data type of the  tensor
 b[:2, :2, :1]

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [ ]:
# tf.add(b, 50)
# tf.subtract(b, 4)
# tf.multiply(b, 54.5)
b = tf.reshape(b, [2, 2, 3])
b
# tf.math.multiply(b, 32)
tf.math.add(b, 42)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[43., 43., 43.],
        [43., 43., 43.]],

       [[43., 43., 43.],
        [43., 43., 43.]]], dtype=float32)>

In [ ]:
# b[..., tf.newaxis]
tf.expand_dims(b, axis= -2) #both are used in adding extra dimensions to the tensor

<tf.Tensor: shape=(2, 2, 1, 3), dtype=float32, numpy=
array([[[[1., 1., 1.]],

        [[1., 1., 1.]]],


       [[[1., 1., 1.]],

        [[1., 1., 1.]]]], dtype=float32)>

In [ ]:
import numpy as np #converting a numpy array into a tensor and reshaping it
c = np.arange(1, 25)
c = tf.constant(c)
print(c)
c = tf.reshape(c, [2, 2, 3, 2])
c


tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int64)


<tf.Tensor: shape=(2, 2, 3, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16],
         [17, 18]],

        [[19, 20],
         [21, 22],
         [23, 24]]]])>

In [ ]:
# Multiplying of tensor matrixes
d = tf.constant([[2, 3],
                 [5, 6],
                 [4, 8]])
e = tf.constant([[3, 4, 5],
                 [2, 8, 6]])
E = tf.linalg.matmul(d, e)
E
# tf.size(E).numpy()

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12, 32, 28],
       [27, 68, 61],
       [28, 80, 68]], dtype=int32)>

In [ ]:
tf.transpose(E) #transpose of tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12, 27, 28],
       [32, 68, 80],
       [28, 61, 68]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(E), d)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 271,  422],
       [ 724, 1144],
       [ 633,  994]], dtype=int32)>

In [ ]:
f = tf.tensordot(d, e, axes=0)
f

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[ 6,  8, 10],
         [ 4, 16, 12]],

        [[ 9, 12, 15],
         [ 6, 24, 18]]],


       [[[15, 20, 25],
         [10, 40, 30]],

        [[18, 24, 30],
         [12, 48, 36]]],


       [[[12, 16, 20],
         [ 8, 32, 24]],

        [[24, 32, 40],
         [16, 64, 48]]]], dtype=int32)>

In [ ]:
# reduced precision(dtype of floats from 32 to 16)
f = tf.cast(f, dtype=tf.float16) #here I converted the dtpye from int to float
f, f.dtype

(<tf.Tensor: shape=(3, 2, 2, 3), dtype=float16, numpy=
 array([[[[ 6.,  8., 10.],
          [ 4., 16., 12.]],
 
         [[ 9., 12., 15.],
          [ 6., 24., 18.]]],
 
 
        [[[15., 20., 25.],
          [10., 40., 30.]],
 
         [[18., 24., 30.],
          [12., 48., 36.]]],
 
 
        [[[12., 16., 20.],
          [ 8., 32., 24.]],
 
         [[24., 32., 40.],
          [16., 64., 48.]]]], dtype=float16)>, tf.float16)

In [ ]:
g = tf.cast(f, dtype=tf.int8) # the float to int again
g, g.dtype

(<tf.Tensor: shape=(3, 2, 2, 3), dtype=int8, numpy=
 array([[[[ 6,  8, 10],
          [ 4, 16, 12]],
 
         [[ 9, 12, 15],
          [ 6, 24, 18]]],
 
 
        [[[15, 20, 25],
          [10, 40, 30]],
 
         [[18, 24, 30],
          [12, 48, 36]]],
 
 
        [[[12, 16, 20],
          [ 8, 32, 24]],
 
         [[24, 32, 40],
          [16, 64, 48]]]], dtype=int8)>, tf.int8)

In [ ]:
# Aggregating tensors
A1 = tf.constant([[-3, 5],
                  [-4, 9],
                  [4.5, -3]])
# A1.ndim
tf.abs(A1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3. , 5. ],
       [4. , 9. ],
       [4.5, 3. ]], dtype=float32)>

In [ ]:
A2 = tf.cast(A1, dtype = tf.int16)
A2 = tf.reshape(A2, [2, 3, 1])
print("The tensor", "\n", A2)
print('The absolute value of the tensor', "\n", tf.abs(A2)), "\n"
A2.dtype, tf.size(A2).numpy()

The tensor 
 tf.Tensor(
[[[-3]
  [ 5]
  [-4]]

 [[ 9]
  [ 4]
  [-3]]], shape=(2, 3, 1), dtype=int16)
The absolute value of the tensor 
 tf.Tensor(
[[[3]
  [5]
  [4]]

 [[9]
  [4]
  [3]]], shape=(2, 3, 1), dtype=int16)


(tf.int16, 6)

In [151]:
tf.size(A2).numpy(), tf.shape(A2)

(6, <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 1], dtype=int32)>)