# In this notebook, its more about the fundamentals of tensors using Tensorflow



In [40]:
# Import TensorFLow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [41]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [42]:
# Check the number of dimensions of a tesor (ndim stands for number of dimesion)
scalar.ndim

0

In [43]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [44]:
# Check the dimension of the vector
vector.ndim

1

In [45]:
# Create a matrix(has more than one dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [46]:
# Check the dimension of the matrix
matrix.ndim

2

In [47]:
# Create anothter type of matrix
ano_matrix = tf.constant([[3., 2.],
                          [4., 3.],
                          [4., 8.]], dtype=tf.float16) #specifying the data type

ano_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[3., 2.],
       [4., 3.],
       [4., 8.]], dtype=float16)>

In [48]:
# check the nnumber of dimensions
ano_matrix.ndim

2

In [49]:
#  Creating a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [50]:
# Check the number of dimension
tensor.ndim

3

In [51]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor 

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [52]:
# checking the indexing
changeable_tensor[1] 

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [53]:
# Changing the values in the index
changeable_tensor[1].assign(10)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

In [54]:
# Creating random tensors 
random_1 = tf.random.Generator.from_seed(42)  #set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [55]:
# Shuffle the order of elements in a tensor
not_shuffled = tf.constant([[8, 9],
                            [3, 6],
                            [2, 7]])
not_shuffled
tf.random.shuffle(not_shuffled)

# adding a seed(This creates a random shuffe)
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled, seed = 7)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 6],
       [8, 9],
       [2, 7]], dtype=int32)>

In [56]:
A = tf.constant([[2,3,4],
                [2, 4, 5]])
# A.ndim
# tf.size(A).numpy()
# print(tf.shape(A).numpy())
# A.shape

In [57]:
# a = tf.zeros([2, 2])
# a
b = tf.ones([3, 4])
b = tf.reshape(b, [2,3,2])
b + 8, b

(<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
 array([[[9., 9.],
         [9., 9.],
         [9., 9.]],
 
        [[9., 9.],
         [9., 9.],
         [9., 9.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
 array([[[1., 1.],
         [1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.],
         [1., 1.]]], dtype=float32)>)