Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

Find the shape, rank and size of the tensors you created in 1.

Create two tensors containing random values between 0 and 1 with shape [5, 300].

Multiply the two tensors you created in 3 using matrix multiplication.

Multiply the two tensors you created in 3 using dot product.

Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

Find the min and max values of the tensor you created in 6.

Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

One-hot encode the tensor you created in 9.

In [1]:
import tensorflow as tf
print (tf.__version__)

2.8.2


In [2]:
# creating a scaler, vector, matrix and tensor
sc = tf.constant(2)
vc = tf.constant([2, 3])
ma = tf.constant([[10, 3],
                  [5, 8]])
ts = tf.constant([[[10, 5],
                   [3, 5]],
                  [[7, 9],
                   [8, 6]]])
sc, vc, ma, ts

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  3],
        [ 5,  8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[10,  5],
         [ 3,  5]],
 
        [[ 7,  9],
         [ 8,  6]]], dtype=int32)>)

In [3]:
# dimensions of the variables created
sc.ndim, vc.ndim, ma.ndim, ts.ndim

(0, 1, 2, 3)

In [4]:
# checking the sizes of the tensor
tf.size(sc), tf.size(vc), tf.size(ma), tf.size(ts)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [10]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300].
A1 = tf.random.Generator.from_seed(42)
A1 = A1.normal(shape=(5,300))
A2 = tf.random.Generator.from_seed(40)
A2 = A2.normal(shape=(5,300))
A1, A2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
         -1.0722276 , -0.00586287],
        [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
          1.155565  , -0.10707551],
        [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
          1.216793  , -1.24293   ],
        [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 ,
         -0.73970354,  0.0177109 ],
        [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
          0.5656089 ,  0.18439196]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345, -0.48535708, ..., -1.655111  ,
          0.20270453, -0.05907417],
        [-0.08876546, -0.2818856 , -1.2894468 , ..., -0.36720887,
         -0.40844494, -0.9370698 ],
        [-0.75371194, -1.7472465 , -0.26269418, ..., -2.465845  ,
         -1.1038724 ,  0.5590708 ],
        [-0.9807223 , -0.16120234,  1.0154027 , ...,  0.3698049 

In [12]:
# multiplying both tensors
tf.multiply(A1, A2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[-5.9734756e-01, -3.6945023e-02, -3.6862995e-02, ...,
         1.7740041e+00, -2.1734540e-01,  3.4634423e-04],
       [ 7.8158900e-02,  9.1404356e-02,  3.2038987e+00, ...,
        -6.0633913e-02, -4.7198468e-01,  1.0033723e-01],
       [ 1.1536902e+00,  1.5061775e+00,  4.2974517e-02, ...,
        -8.4549105e-01, -1.3431841e+00, -6.9488591e-01],
       [-8.2698685e-01,  3.7689015e-02,  4.3422660e-01, ...,
        -3.8565892e-01,  3.0549249e-01,  1.6156685e-02],
       [-5.2119963e-02,  1.2068667e+00,  1.6118759e+00, ...,
         2.5870258e-02, -3.8134153e-03,  1.5465494e-01]], dtype=float32)>

In [14]:
# Multiplying using dotproduct
A2 = tf.reshape(A2, [300,5])
tf.tensordot(A1, A2, axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-11.416164 , -25.903225 ,  -2.026891 ,  14.872477 , -14.520887 ],
       [-12.685434 , -12.168114 , -13.383297 , -16.040981 ,  30.11199  ],
       [ -5.931279 ,  33.133007 ,   3.102962 ,  15.162788 , -32.050903 ],
       [ 12.049271 , -39.353737 , -31.531788 ,  -7.3040724, -15.2411585],
       [ -1.9300346,  24.349224 ,   4.8790627,  41.730118 ,  23.65246  ]],
      dtype=float32)>

In [16]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
A3 = tf.random.Generator.from_seed(42)
A3 = A3.normal(shape=(224, 224, 3))
A3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        ...,
        [ 0.07099114, -0.5095768 ,  0.3482001 ],
        [ 0.15985982, -1.9042184 ,  0.9690504 ],
        [ 0.16251186, -0.07330752, -0.360591  ]],

       [[ 0.18739441, -0.73353654,  1.2104433 ],
        [ 1.5603006 , -0.48115277,  0.6335167 ],
        [-0.5612103 ,  0.06994031,  1.6807095 ],
        ...,
        [-1.9460293 , -0.7977275 ,  0.03092833],
        [ 0.8297488 ,  0.12179119,  1.0506107 ],
        [-1.3097638 ,  0.92536974, -1.1787732 ]],

       [[-0.21711822, -0.73974085, -1.3077081 ],
        [-0.7502274 , -0.37715855, -0.30130875],
        [ 1.0943383 ,  0.255803  ,  0.8011465 ],
        ...,
        [-0.32833767, -0.7794747 ,  0.20049338],
        [-0.09002841,  0.07243238, -0.81940895],
        [ 0.3171264 , -1.6143695 , -1.6824651 ]],

       ...,

     

In [18]:
tf.reduce_min(A3), tf.reduce_max(A3)

(<tf.Tensor: shape=(), dtype=float32, numpy=-4.848316>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.4032865>)

In [20]:
# Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
A4 = tf.random.Generator.from_seed(41)
A4 = A4.normal(shape=(1, 224, 224, 3))
A4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[ 0.31662667, -1.4391748 ,  0.58923835],
         [-1.4268045 , -0.7565803 , -0.06854702],
         [ 0.07595026, -1.2573844 , -0.23193763],
         ...,
         [-0.6170378 , -0.63352513,  0.5734031 ],
         [-0.2029834 ,  0.07099114, -0.5095768 ],
         [ 0.3482001 ,  0.15985982, -1.9042184 ]],

        [[ 0.9690504 ,  0.16251186, -0.07330752],
         [-0.360591  ,  0.18739441, -0.73353654],
         [ 1.2104433 ,  1.5603006 , -0.48115277],
         ...,
         [-0.01129926,  1.6280283 ,  0.54630095],
         [ 1.7401857 , -1.9460293 , -0.7977275 ],
         [ 0.03092833,  0.8297488 ,  0.12179119]],

        [[ 1.0506107 , -1.3097638 ,  0.92536974],
         [-1.1787732 , -0.21711822, -0.73974085],
         [-1.3077081 , -0.7502274 , -0.37715855],
         ...,
         [-0.4088551 ,  1.0206331 , -0.6284685 ],
         [-0.08360445, -0.32833767, -0.7794747 ],
         [ 0.20049338, -0.09002841,  0.0724323

In [21]:
tf.squeeze(A4)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 0.31662667, -1.4391748 ,  0.58923835],
        [-1.4268045 , -0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 , -0.23193763],
        ...,
        [-0.6170378 , -0.63352513,  0.5734031 ],
        [-0.2029834 ,  0.07099114, -0.5095768 ],
        [ 0.3482001 ,  0.15985982, -1.9042184 ]],

       [[ 0.9690504 ,  0.16251186, -0.07330752],
        [-0.360591  ,  0.18739441, -0.73353654],
        [ 1.2104433 ,  1.5603006 , -0.48115277],
        ...,
        [-0.01129926,  1.6280283 ,  0.54630095],
        [ 1.7401857 , -1.9460293 , -0.7977275 ],
        [ 0.03092833,  0.8297488 ,  0.12179119]],

       [[ 1.0506107 , -1.3097638 ,  0.92536974],
        [-1.1787732 , -0.21711822, -0.73974085],
        [-1.3077081 , -0.7502274 , -0.37715855],
        ...,
        [-0.4088551 ,  1.0206331 , -0.6284685 ],
        [-0.08360445, -0.32833767, -0.7794747 ],
        [ 0.20049338, -0.09002841,  0.07243238]],

       ...,

     

In [27]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
A5 = tf.constant([2, 5, 6, 7, 8, 6, 7, 4, 3, 9])
A5.shape

TensorShape([10])

In [33]:
# Index with the max value
tf.argmax(A5)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [34]:
# One-hot encode the tensor you created in 9.
tf.one_hot(A5, depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>